#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

from Application import FlixApplication

if __name__ == "__main__":
	app = FlixApplication()	 # create the GUI
	app.run()
	Gtk.main()	 # continuous function for running GTK applications
